var logger = new Logger('Client:tutorial');

Logger.setLevel('Client:tutorial', 'trace');
// Logger.setLevel('Client:tutorial', 'debug');
// Logger.setLevel('Client:tutorial', 'info');
// Logger.setLevel('Client:tutorial', 'warn');

LocalWords = new Mongo.Collection(null);
var currentStart = 0;
var currentEnd = 0;

Template.tutorial.rendered = function() {
  Session.set("highlightState", "none");


}

Template.tutorial.helpers({
  testWords: function() {
    return LocalWords.find().fetch();;
  },
  goldWords: function() {
    return goldTutorialWords;
  },
  highlightDescription: function() {
    if (!Session.equals("highlightState", "none")) {
      return highlightDescriptions[Session.get("highlightState")]
    } else {
      return "are just words";
    }
  },
  statusBackground: function() {
    if (Session.equals("highlightState", "background")) {
      return "ing";
    } else {
      return "";
    }
  },
  statusPurpose: function() {
    if (Session.equals("highlightState", "purpose")) {
      return "ing";
    } else {
      return "";
    }
  },
  statusMechanism: function() {
    if (Session.equals("highlightState", "mechanism")) {
      return "ing";
    } else {
      return "";
    }
  },
  statusFinding: function() {
    if (Session.equals("highlightState", "finding")) {
      return "ing";
    } else {
      return "";
    }
  },
  statusUnmark: function() {
    if (Session.equals("highlightState", "unmark")) {
      return "ing";
    } else {
      return "";
    }
  },
  score: function() {
    return scoreTutorial();
  }
})

Template.goldWord.helpers({
    keyType: function() {
      var userID = "gold";
      if (isInList(userID, this.highlightsPurpose)) {
          // logger.debug("isPurpose is true");
          return "key-purpose";
      } else if (isInList(userID, this.highlightsMechanism)) {
          return "key-mechanism"
      } else if (isInList(userID, this.highlightsFindings)) {
          return "key-finding"
      } else if (isInList(userID, this.highlightsBackground)) {
          return "key-background"
      } else {
        return "key-neutral"
      }
    },
});

Template.tutorial.events({
    'mouseup': function(event) {
      // catch mouseups that happen if ppl are too quick when switching highlights
      if (Session.equals("isHighlighting", true)) {
        logger.debug("Mouse up out of the doc, ending highlight...");
        Session.set("isHighlighting", false);
      }
    },
    'click .test' : function() {
      var user = Session.get("currentUser");
      var score = scoreTutorial();
      var highlights = LocalWords.find().fetch();
      EventLogger.logCheckTutorialAccuracy(user, score, highlights)
      // var dataStatus = checkData();
      var dataStatus = "allGood";
      if (dataStatus === "allGood") {
        $('.gold-example').toggle();
        // $('trial-result-filler').hide();
        $('.trial-result').show();
        $('.trial-names').show();
        $('.continue').prop('disabled', false);
        UserManager.recordTutorialAccuracy(user, score, highlights)
      } else {
        alert(checkWarnings[dataStatus])
      }
      // // var dataOk = true;
      // if (isAnnotatedBy(Session.get("currentUser")) && mostlyAnnotatedBy(Session.get("currentUser"))) {
      //   alert("")
      // } else if (!isAnnotatedBy(Session.get("currentUser"))) {
      //   alert("Please use all of the highlight types! " +
      //   "If you really think one of the highlight types is missing from the abstract, just mark a random punctuation with it.");
      // } else if (!mostlyAnnotatedBy(Session.get("currentUser"))) {
      //   alert("Please highlight all of the relevant parts of the abstract! " +
      //   "Most abstracts only have 1 sentence at most that doesn't fit into our highlight types.");
      // } else {
      //   $('.gold-example').toggle();
      //   $('.trial-result').toggle();
      // }
    },
    'click .continue' : function() {
        logger.debug("User clicked continue");
        EventLogger.logFinishTutorial();
        var user = Session.get("currentUser");
        if (user) {
            var doc = DocumentManager.sampleDocument(user._id);
            logger.trace("Sending user to annotation task with document " + JSON.stringify(doc));
            Router.go("Annotate", {userID: user._id,
                                    docID: doc._id});
        } else {
            logger.warn("User is not logged in");
            alert("You need to have entered your MTurkID to continue");
            Router.go("Land")
        }
    },
    'click .init-highlight': function(event) {
      var button = event.currentTarget;
      $('.init-highlight').removeClass("active-" + Session.get("highlightState"));
      $('.highlight-description').show();
      $('.highlight-description').removeClass("key-" + Session.get("highlightState"));
      if (!isInList("unmark", button.classList)) {
        if (isInList("purpose", button.classList)) {
          Session.set("highlightState", "purpose");
        } else if (isInList("mechanism", button.classList)) {
          Session.set("highlightState", "mechanism");
        } else if (isInList("finding", button.classList)) {
          Session.set("highlightState", "finding");
        } else if (isInList("background", button.classList)) {
          Session.set("highlightState", "background");
        } else {
        }
        // button.classList.add("active-" + Session.get("highlightState"));
        $('.highlight-description').addClass("key-" + Session.get("highlightState"));
      } else {
        Session.set("highlightState", "unmark");
        $('.highlight-description').hide();
      }
      button.classList.add("active-" + Session.get("highlightState"));
    },
});

Template.tutorialWord.rendered = function(){
  // var doc = Session.get("currentDoc");
  // logger.trace("Current doc: " + JSON.stringify(doc));
  // var dbWords = Words.find({docID: doc._id}).fetch();
  // logger.trace(dbWords.length + "dbWords");
  // if (LocalWords.find().count() < 1) { // newly created local
  //   // LocalWords = new Mongo.Collection(null);
  //   dbWords.forEach(function(word) {
  //     // logger.trace("Inserting word " + JSON.stringify(word) + " into local words collection");
  //     LocalWords.insert(word);
  //   });
  // } else { // refreshed, or going from next page
  //   var randomWord = LocalWords.findOne();
  //   if (!randomWord.hasOwnProperty("sentenceID")) {
  //     // reset if we're coming from the tutorial page
  //     LocalWords = new Mongo.Collection(null);
  //     dbWords.forEach(function(word) {
  //       // logger.trace("Inserting word " + JSON.stringify(word) + " into local words collection");
  //       LocalWords.insert(word);
  //     });
  //   }
  // }
  // logger.trace(LocalWords.find().count() + "local words");
  logger.debug("Rendered word...");
}

Template.tutorialWord.helpers({
    keyType: function() {
      var userID = Session.get("currentUser")._id;
      if (isInList(userID, this.highlightsPurpose)) {
          // logger.debug("isPurpose is true");
          return "key-purpose";
      } else if (isInList(userID, this.highlightsMechanism)) {
          return "key-mechanism"
      } else if (isInList(userID, this.highlightsFindings)) {
          return "key-finding"
      } else if (isInList(userID, this.highlightsBackground)) {
          return "key-background"
      } else {
        return "key-neutral"
      }
    },
});

Template.tutorialWord.events({
    'mousedown .token': function(event) {
      if (Session.get("highlightState") != "none") {
          logger.debug("Begin highlight");
          Session.set("isHighlighting", true);
          var word = event.currentTarget;
          logger.trace(word.innerHTML);
          var wordID = trimFromString(word.id, "word-");
          // currentStart.s = Sentences.findOne(Words.findOne(wordID).sentenceID).psn;
          currentStart = LocalWords.findOne(wordID).globalPsn;
          markWord(wordID);
      }
    },

    'mouseup .token': function(event) {
      logger.debug("End highlight");
      Session.set("isHighlighting", false);
    },

    'mouseover .token': function(event) {
      logger.debug("Hovering over token");
      if (Session.get("isHighlighting")) {
        var word = event.currentTarget;
        logger.trace(word.innerHTML);
        var wordID = trimFromString(word.id, "word-");
        // currentEnd.s = Sentences.findOne(Words.findOne(wordID).sentenceID).psn;
        // currentEnd.w = Words.findOne(wordID).sequence;
        currentEnd = LocalWords.findOne(wordID).globalPsn;
        logger.trace("Current start: " + currentStart);
        logger.trace("Current end: " + currentEnd);

        var selectedWords = LocalWords.find({//docID: Session.get("currentDoc")._id,
                                        globalPsn: {$gte: currentStart,
                                                    $lte: currentEnd}
                                        }).fetch();
        logger.trace("Selected words: " + selectedWords);
        // mark all of these words
        selectedWords.forEach(function(w) {
          markWord(w._id);
        });
      }
    },
})

var scoreTutorial = function() {
  var highlightedWords = LocalWords.find().fetch();
  var numCorrect = 0;
  for (i=0; i < highlightedWords.length; i++) {
    if (highlightType(highlightedWords[i]) === highlightType(goldTutorialWords[i])) {
      numCorrect += 1;
    }
  }
  var score = numCorrect/highlightedWords.length*100;
  return score.toString().substring(0,4) + "%";
}

var highlightType = function(word) {
  /*
  Might regret writing this. Dumb greedy function that just
  returns the last highlight field in the list of fields that has any user who marked it.
  */
  var fields = [
    "highlightsPurpose",
    "highlightsMechanism",
    "highlightsFindings",
    "highlightsBackground",
  ]
  var result = "none";
  fields.forEach(function(field) {
    if (word[field].length > 0) {
      result = field;
    }
  });
  return result;
}

// highlightDescriptions = {
//   "purpose": "What do the paper's authors want to do or know?",
//   "mechanism": "How did the paper's authors do it or find out?",
//   "finding": "Did it work? What did the paper's authors find out?",
//   "background": "What is the intellectual context of this work? What other (higher-level) goals/questions can be furthered by this work? How might this help other research(ers)?",
//   "unmark": "",
// }

goldTutorialWords = [
  {
     "globalpsn":0
    ,"highlightsFindings":[]
    ,"content":"Researchers"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":["gold"]
    ,"_id":"word-0"
  },
  {
     "globalpsn":1
    ,"highlightsFindings":[]
    ,"content":"and"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":["gold"]
    ,"_id":"word-1"
  },
  {
     "globalpsn":2
    ,"highlightsFindings":[]
    ,"content":"theorists"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":["gold"]
    ,"_id":"word-2"
  },
  {
     "globalpsn":3
    ,"highlightsFindings":[]
    ,"content":"have"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":["gold"]
    ,"_id":"word-3"
  },
  {
     "globalpsn":4
    ,"highlightsFindings":[]
    ,"content":"proposed"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":["gold"]
    ,"_id":"word-4"
  },
  {
     "globalpsn":5
    ,"highlightsFindings":[]
    ,"content":"that"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-5"
  },
  {
     "globalpsn":6
    ,"highlightsFindings":[]
    ,"content":"feelings"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-6"
  },
  {
     "globalpsn":7
    ,"highlightsFindings":[]
    ,"content":"of"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-7"
  },
  {
     "globalpsn":8
    ,"highlightsFindings":[]
    ,"content":"attachment"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-8"
  },
  {
     "globalpsn":9
    ,"highlightsFindings":[]
    ,"content":"to"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-9"
  },
  {
     "globalpsn":10
    ,"highlightsFindings":[]
    ,"content":"subgroups"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-10"
  },
  {
     "globalpsn":11
    ,"highlightsFindings":[]
    ,"content":"within"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-11"
  },
  {
     "globalpsn":12
    ,"highlightsFindings":[]
    ,"content":"a"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-12"
  },
  {
     "globalpsn":13
    ,"highlightsFindings":[]
    ,"content":"larger"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-13"
  },
  {
     "globalpsn":14
    ,"highlightsFindings":[]
    ,"content":"online"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-14"
  },
  {
     "globalpsn":15
    ,"highlightsFindings":[]
    ,"content":"community"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-15"
  },
  {
     "globalpsn":16
    ,"highlightsFindings":[]
    ,"content":"or"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-16"
  },
  {
     "globalpsn":17
    ,"highlightsFindings":[]
    ,"content":"site"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-17"
  },
  {
     "globalpsn":18
    ,"highlightsFindings":[]
    ,"content":"can"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-18"
  },
  {
     "globalpsn":19
    ,"highlightsFindings":[]
    ,"content":"increase"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-19"
  },
  {
     "globalpsn":20
    ,"highlightsFindings":[]
    ,"content":"users"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-20"
  },
  {
     "globalpsn":21
    ,"highlightsFindings":[]
    ,"content":"'"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-21"
  },
  {
     "globalpsn":22
    ,"highlightsFindings":[]
    ,"content":"loyalty"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-22"
  },
  {
     "globalpsn":23
    ,"highlightsFindings":[]
    ,"content":"to"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-23"
  },
  {
     "globalpsn":24
    ,"highlightsFindings":[]
    ,"content":"the"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-24"
  },
  {
     "globalpsn":25
    ,"highlightsFindings":[]
    ,"content":"site"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-25"
  },
  {
     "globalpsn":26
    ,"highlightsFindings":[]
    ,"content":"."
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-26"
  },
  {
     "globalpsn":27
    ,"highlightsFindings":[]
    ,"content":"They"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":["gold"]
    ,"_id":"word-27"
  },
  {
     "globalpsn":28
    ,"highlightsFindings":[]
    ,"content":"have"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":["gold"]
    ,"_id":"word-28"
  },
  {
     "globalpsn":29
    ,"highlightsFindings":[]
    ,"content":"identified"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":["gold"]
    ,"_id":"word-29"
  },
  {
     "globalpsn":30
    ,"highlightsFindings":[]
    ,"content":"two"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-30"
  },
  {
     "globalpsn":31
    ,"highlightsFindings":[]
    ,"content":"types"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-31"
  },
  {
     "globalpsn":32
    ,"highlightsFindings":[]
    ,"content":"of"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-32"
  },
  {
     "globalpsn":33
    ,"highlightsFindings":[]
    ,"content":"attachment,"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-33"
  },
  {
     "globalpsn":34
    ,"highlightsFindings":[]
    ,"content":"with"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-34"
  },
  {
     "globalpsn":35
    ,"highlightsFindings":[]
    ,"content":"distinct"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-35"
  },
  {
     "globalpsn":36
    ,"highlightsFindings":[]
    ,"content":"causes"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-36"
  },
  {
     "globalpsn":37
    ,"highlightsFindings":[]
    ,"content":"and"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-37"
  },
  {
     "globalpsn":38
    ,"highlightsFindings":[]
    ,"content":"consequences"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-38"
  },
  {
     "globalpsn":39
    ,"highlightsFindings":[]
    ,"content":"."
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-39"
  },
  {
     "globalpsn":40
    ,"highlightsFindings":[]
    ,"content":"With"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-40"
  },
  {
     "globalpsn":41
    ,"highlightsFindings":[]
    ,"content":"bond-based"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-41"
  },
  {
     "globalpsn":42
    ,"highlightsFindings":[]
    ,"content":"attachment,"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-42"
  },
  {
     "globalpsn":43
    ,"highlightsFindings":[]
    ,"content":"people"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-43"
  },
  {
     "globalpsn":44
    ,"highlightsFindings":[]
    ,"content":"feel"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-44"
  },
  {
     "globalpsn":45
    ,"highlightsFindings":[]
    ,"content":"connections"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-45"
  },
  {
     "globalpsn":46
    ,"highlightsFindings":[]
    ,"content":"to"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-46"
  },
  {
     "globalpsn":47
    ,"highlightsFindings":[]
    ,"content":"other"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-47"
  },
  {
     "globalpsn":48
    ,"highlightsFindings":[]
    ,"content":"group"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-48"
  },
  {
     "globalpsn":49
    ,"highlightsFindings":[]
    ,"content":"members,"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-49"
  },
  {
     "globalpsn":50
    ,"highlightsFindings":[]
    ,"content":"while"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-50"
  },
  {
     "globalpsn":51
    ,"highlightsFindings":[]
    ,"content":"with"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-51"
  },
  {
     "globalpsn":52
    ,"highlightsFindings":[]
    ,"content":"identity-based"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-52"
  },
  {
     "globalpsn":53
    ,"highlightsFindings":[]
    ,"content":"attachment"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-53"
  },
  {
     "globalpsn":54
    ,"highlightsFindings":[]
    ,"content":"they"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-54"
  },
  {
     "globalpsn":55
    ,"highlightsFindings":[]
    ,"content":"feel"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-55"
  },
  {
     "globalpsn":56
    ,"highlightsFindings":[]
    ,"content":"connections"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-56"
  },
  {
     "globalpsn":57
    ,"highlightsFindings":[]
    ,"content":"to"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-57"
  },
  {
     "globalpsn":58
    ,"highlightsFindings":[]
    ,"content":"the"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-58"
  },
  {
     "globalpsn":59
    ,"highlightsFindings":[]
    ,"content":"group"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-59"
  },
  {
     "globalpsn":60
    ,"highlightsFindings":[]
    ,"content":"as"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-60"
  },
  {
     "globalpsn":61
    ,"highlightsFindings":[]
    ,"content":"a"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-61"
  },
  {
     "globalpsn":62
    ,"highlightsFindings":[]
    ,"content":"whole"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-62"
  },
  {
     "globalpsn":63
    ,"highlightsFindings":[]
    ,"content":"."
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-63"
  },
  {
     "globalpsn":64
    ,"highlightsFindings":[]
    ,"content":"In"
    ,"highlightsMechanism":["gold"]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-64"
  },
  {
     "globalpsn":65
    ,"highlightsFindings":[]
    ,"content":"two"
    ,"highlightsMechanism":["gold"]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-65"
  },
  {
     "globalpsn":66
    ,"highlightsFindings":[]
    ,"content":"experiments"
    ,"highlightsMechanism":["gold"]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-66"
  },
  {
     "globalpsn":67
    ,"highlightsFindings":[]
    ,"content":"we"
    ,"highlightsMechanism":["gold"]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-67"
  },
  {
     "globalpsn":68
    ,"highlightsFindings":[]
    ,"content":"show"
    ,"highlightsMechanism":["gold"]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-68"
  },
  {
     "globalpsn":69
    ,"highlightsFindings":[]
    ,"content":"that"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-69"
  },
  {
     "globalpsn":70
    ,"highlightsFindings":[]
    ,"content":"these"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-70"
  },
  {
     "globalpsn":71
    ,"highlightsFindings":[]
    ,"content":"feelings"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-71"
  },
  {
     "globalpsn":72
    ,"highlightsFindings":[]
    ,"content":"of"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-72"
  },
  {
     "globalpsn":73
    ,"highlightsFindings":[]
    ,"content":"attachment"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-73"
  },
  {
     "globalpsn":74
    ,"highlightsFindings":[]
    ,"content":"to"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-74"
  },
  {
     "globalpsn":75
    ,"highlightsFindings":[]
    ,"content":"subgroups"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-75"
  },
  {
     "globalpsn":76
    ,"highlightsFindings":["gold"]
    ,"content":"increase"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-76"
  },
  {
     "globalpsn":77
    ,"highlightsFindings":[]
    ,"content":"loyalty"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-77"
  },
  {
     "globalpsn":78
    ,"highlightsFindings":[]
    ,"content":"to"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-78"
  },
  {
     "globalpsn":79
    ,"highlightsFindings":[]
    ,"content":"the"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-79"
  },
  {
     "globalpsn":80
    ,"highlightsFindings":[]
    ,"content":"larger"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-80"
  },
  {
     "globalpsn":81
    ,"highlightsFindings":[]
    ,"content":"community"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-81"
  },
  {
     "globalpsn":82
    ,"highlightsFindings":[]
    ,"content":"."
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-82"
  },
  {
     "globalpsn":83
    ,"highlightsFindings":[]
    ,"content":"Communication"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-83"
  },
  {
     "globalpsn":84
    ,"highlightsFindings":[]
    ,"content":"with"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-84"
  },
  {
     "globalpsn":85
    ,"highlightsFindings":[]
    ,"content":"other"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-85"
  },
  {
     "globalpsn":86
    ,"highlightsFindings":[]
    ,"content":"people"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-86"
  },
  {
     "globalpsn":87
    ,"highlightsFindings":[]
    ,"content":"in"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-87"
  },
  {
     "globalpsn":88
    ,"highlightsFindings":[]
    ,"content":"a"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-88"
  },
  {
     "globalpsn":89
    ,"highlightsFindings":[]
    ,"content":"subgroup"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-89"
  },
  {
     "globalpsn":90
    ,"highlightsFindings":[]
    ,"content":"but"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-90"
  },
  {
     "globalpsn":91
    ,"highlightsFindings":[]
    ,"content":"not"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-91"
  },
  {
     "globalpsn":92
    ,"highlightsFindings":[]
    ,"content":"simple"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-92"
  },
  {
     "globalpsn":93
    ,"highlightsFindings":[]
    ,"content":"awareness"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-93"
  },
  {
     "globalpsn":94
    ,"highlightsFindings":[]
    ,"content":"of"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-94"
  },
  {
     "globalpsn":95
    ,"highlightsFindings":[]
    ,"content":"them"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-95"
  },
  {
     "globalpsn":96
    ,"highlightsFindings":[]
    ,"content":"increases"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-96"
  },
  {
     "globalpsn":97
    ,"highlightsFindings":[]
    ,"content":"attachment"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-97"
  },
  {
     "globalpsn":98
    ,"highlightsFindings":[]
    ,"content":"to"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-98"
  },
  {
     "globalpsn":99
    ,"highlightsFindings":[]
    ,"content":"the"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-99"
  },
  {
     "globalpsn":100
    ,"highlightsFindings":[]
    ,"content":"larger"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-100"
  },
  {
     "globalpsn":101
    ,"highlightsFindings":[]
    ,"content":"community"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-101"
  },
  {
     "globalpsn":102
    ,"highlightsFindings":[]
    ,"content":"."
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-102"
  },
  {
     "globalpsn":103
    ,"highlightsFindings":[]
    ,"content":"By"
    ,"highlightsMechanism":["gold"]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-103"
  },
  {
     "globalpsn":104
    ,"highlightsFindings":[]
    ,"content":"varying"
    ,"highlightsMechanism":["gold"]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-104"
  },
  {
     "globalpsn":105
    ,"highlightsFindings":[]
    ,"content":"how"
    ,"highlightsMechanism":["gold"]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-105"
  },
  {
     "globalpsn":106
    ,"highlightsFindings":[]
    ,"content":"the"
    ,"highlightsMechanism":["gold"]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-106"
  },
  {
     "globalpsn":107
    ,"highlightsFindings":[]
    ,"content":"communication"
    ,"highlightsMechanism":["gold"]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-107"
  },
  {
     "globalpsn":108
    ,"highlightsFindings":[]
    ,"content":"is"
    ,"highlightsMechanism":["gold"]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-108"
  },
  {
     "globalpsn":109
    ,"highlightsFindings":[]
    ,"content":"structured,"
    ,"highlightsMechanism":["gold"]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-109"
  },
  {
     "globalpsn":110
    ,"highlightsFindings":[]
    ,"content":"between"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-110"
  },
  {
     "globalpsn":111
    ,"highlightsFindings":[]
    ,"content":"dyads"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-111"
  },
  {
     "globalpsn":112
    ,"highlightsFindings":[]
    ,"content":"or"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-112"
  },
  {
     "globalpsn":113
    ,"highlightsFindings":[]
    ,"content":"with"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-113"
  },
  {
     "globalpsn":114
    ,"highlightsFindings":[]
    ,"content":"all"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-114"
  },
  {
     "globalpsn":115
    ,"highlightsFindings":[]
    ,"content":"group"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-115"
  },
  {
     "globalpsn":116
    ,"highlightsFindings":[]
    ,"content":"members"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-116"
  },
  {
     "globalpsn":117
    ,"highlightsFindings":[]
    ,"content":"simultaneously,"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-117"
  },
  {
     "globalpsn":118
    ,"highlightsFindings":["gold"]
    ,"content":"the"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-118"
  },
  {
     "globalpsn":119
    ,"highlightsFindings":["gold"]
    ,"content":"experiments"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-119"
  },
  {
     "globalpsn":120
    ,"highlightsFindings":["gold"]
    ,"content":"show"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-120"
  },
  {
     "globalpsn":121
    ,"highlightsFindings":["gold"]
    ,"content":"that"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-121"
  },
  {
     "globalpsn":122
    ,"highlightsFindings":[]
    ,"content":"bond-"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-122"
  },
  {
     "globalpsn":123
    ,"highlightsFindings":[]
    ,"content":"and"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-123"
  },
  {
     "globalpsn":124
    ,"highlightsFindings":[]
    ,"content":"identity-based"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-124"
  },
  {
     "globalpsn":125
    ,"highlightsFindings":[]
    ,"content":"attachment"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-125"
  },
  {
     "globalpsn":126
    ,"highlightsFindings":[]
    ,"content":"have"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-126"
  },
  {
     "globalpsn":127
    ,"highlightsFindings":[]
    ,"content":"different"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-127"
  },
  {
     "globalpsn":128
    ,"highlightsFindings":[]
    ,"content":"causes"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-128"
  },
  {
     "globalpsn":129
    ,"highlightsFindings":[]
    ,"content":"."
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-129"
  },
  {
     "globalpsn":130
    ,"highlightsFindings":[]
    ,"content":"But"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-130"
  },
  {
     "globalpsn":131
    ,"highlightsFindings":[]
    ,"content":"the"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-131"
  },
  {
     "globalpsn":132
    ,"highlightsFindings":[]
    ,"content":"experiments"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-132"
  },
  {
     "globalpsn":133
    ,"highlightsFindings":[]
    ,"content":"show"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-133"
  },
  {
     "globalpsn":134
    ,"highlightsFindings":[]
    ,"content":"no"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-134"
  },
  {
     "globalpsn":135
    ,"highlightsFindings":[]
    ,"content":"evidence"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-135"
  },
  {
     "globalpsn":136
    ,"highlightsFindings":[]
    ,"content":"that"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-136"
  },
  {
     "globalpsn":137
    ,"highlightsFindings":[]
    ,"content":"bond"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-137"
  },
  {
     "globalpsn":138
    ,"highlightsFindings":[]
    ,"content":"and"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-138"
  },
  {
     "globalpsn":139
    ,"highlightsFindings":[]
    ,"content":"identity"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-139"
  },
  {
     "globalpsn":140
    ,"highlightsFindings":[]
    ,"content":"attachment"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-140"
  },
  {
     "globalpsn":141
    ,"highlightsFindings":[]
    ,"content":"have"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-141"
  },
  {
     "globalpsn":142
    ,"highlightsFindings":[]
    ,"content":"different"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-142"
  },
  {
     "globalpsn":143
    ,"highlightsFindings":[]
    ,"content":"consequences"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-143"
  },
  {
     "globalpsn":144
    ,"highlightsFindings":[]
    ,"content":"."
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-144"
  },
  {
     "globalpsn":145
    ,"highlightsFindings":[]
    ,"content":"We"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-145"
  },
  {
     "globalpsn":146
    ,"highlightsFindings":[]
    ,"content":"consider"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":["gold"]
    ,"highlightsBackground":[]
    ,"_id":"word-146"
  },
  {
     "globalpsn":147
    ,"highlightsFindings":[]
    ,"content":"both"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-147"
  },
  {
     "globalpsn":148
    ,"highlightsFindings":[]
    ,"content":"theoretical"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-148"
  },
  {
     "globalpsn":149
    ,"highlightsFindings":[]
    ,"content":"and"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-149"
  },
  {
     "globalpsn":150
    ,"highlightsFindings":[]
    ,"content":"methodological"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-150"
  },
  {
     "globalpsn":151
    ,"highlightsFindings":[]
    ,"content":"reasons"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-151"
  },
  {
     "globalpsn":152
    ,"highlightsFindings":[]
    ,"content":"why"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-152"
  },
  {
     "globalpsn":153
    ,"highlightsFindings":[]
    ,"content":"the"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-153"
  },
  {
     "globalpsn":154
    ,"highlightsFindings":[]
    ,"content":"consequences"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-154"
  },
  {
     "globalpsn":155
    ,"highlightsFindings":[]
    ,"content":"of"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-155"
  },
  {
     "globalpsn":156
    ,"highlightsFindings":[]
    ,"content":"bond-based"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-156"
  },
  {
     "globalpsn":157
    ,"highlightsFindings":[]
    ,"content":"and"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-157"
  },
  {
     "globalpsn":158
    ,"highlightsFindings":[]
    ,"content":"identity-based"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-158"
  },
  {
     "globalpsn":159
    ,"highlightsFindings":[]
    ,"content":"attachment"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-159"
  },
  {
     "globalpsn":160
    ,"highlightsFindings":[]
    ,"content":"are"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-160"
  },
  {
     "globalpsn":161
    ,"highlightsFindings":[]
    ,"content":"so"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-161"
  },
  {
     "globalpsn":162
    ,"highlightsFindings":[]
    ,"content":"similar"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-162"
  },
  {
     "globalpsn":163
    ,"highlightsFindings":[]
    ,"content":"."
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"word-163"
  }]


trainTutorialWords = [
  {
     "globalpsn":0
    ,"highlightsFindings":[]
    ,"content":"Researchers"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w0"
  },
  {
     "globalpsn":1
    ,"highlightsFindings":[]
    ,"content":"and"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w1"
  },
  {
     "globalpsn":2
    ,"highlightsFindings":[]
    ,"content":"theorists"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w2"
  },
  {
     "globalpsn":3
    ,"highlightsFindings":[]
    ,"content":"have"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w3"
  },
  {
     "globalpsn":4
    ,"highlightsFindings":[]
    ,"content":"proposed"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w4"
  },
  {
     "globalpsn":5
    ,"highlightsFindings":[]
    ,"content":"that"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w5"
  },
  {
     "globalpsn":6
    ,"highlightsFindings":[]
    ,"content":"feelings"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w6"
  },
  {
     "globalpsn":7
    ,"highlightsFindings":[]
    ,"content":"of"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w7"
  },
  {
     "globalpsn":8
    ,"highlightsFindings":[]
    ,"content":"attachment"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w8"
  },
  {
     "globalpsn":9
    ,"highlightsFindings":[]
    ,"content":"to"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w9"
  },
  {
     "globalpsn":10
    ,"highlightsFindings":[]
    ,"content":"subgroups"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w10"
  },
  {
     "globalpsn":11
    ,"highlightsFindings":[]
    ,"content":"within"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w11"
  },
  {
     "globalpsn":12
    ,"highlightsFindings":[]
    ,"content":"a"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w12"
  },
  {
     "globalpsn":13
    ,"highlightsFindings":[]
    ,"content":"larger"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w13"
  },
  {
     "globalpsn":14
    ,"highlightsFindings":[]
    ,"content":"online"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w14"
  },
  {
     "globalpsn":15
    ,"highlightsFindings":[]
    ,"content":"community"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w15"
  },
  {
     "globalpsn":16
    ,"highlightsFindings":[]
    ,"content":"or"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w16"
  },
  {
     "globalpsn":17
    ,"highlightsFindings":[]
    ,"content":"site"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w17"
  },
  {
     "globalpsn":18
    ,"highlightsFindings":[]
    ,"content":"can"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w18"
  },
  {
     "globalpsn":19
    ,"highlightsFindings":[]
    ,"content":"increase"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w19"
  },
  {
     "globalpsn":20
    ,"highlightsFindings":[]
    ,"content":"users"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w20"
  },
  {
     "globalpsn":21
    ,"highlightsFindings":[]
    ,"content":"'"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w21"
  },
  {
     "globalpsn":22
    ,"highlightsFindings":[]
    ,"content":"loyalty"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w22"
  },
  {
     "globalpsn":23
    ,"highlightsFindings":[]
    ,"content":"to"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w23"
  },
  {
     "globalpsn":24
    ,"highlightsFindings":[]
    ,"content":"the"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w24"
  },
  {
     "globalpsn":25
    ,"highlightsFindings":[]
    ,"content":"site"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w25"
  },
  {
     "globalpsn":26
    ,"highlightsFindings":[]
    ,"content":"."
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w26"
  },
  {
     "globalpsn":27
    ,"highlightsFindings":[]
    ,"content":"They"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w27"
  },
  {
     "globalpsn":28
    ,"highlightsFindings":[]
    ,"content":"have"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w28"
  },
  {
     "globalpsn":29
    ,"highlightsFindings":[]
    ,"content":"identified"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w29"
  },
  {
     "globalpsn":30
    ,"highlightsFindings":[]
    ,"content":"two"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w30"
  },
  {
     "globalpsn":31
    ,"highlightsFindings":[]
    ,"content":"types"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w31"
  },
  {
     "globalpsn":32
    ,"highlightsFindings":[]
    ,"content":"of"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w32"
  },
  {
     "globalpsn":33
    ,"highlightsFindings":[]
    ,"content":"attachment,"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w33"
  },
  {
     "globalpsn":34
    ,"highlightsFindings":[]
    ,"content":"with"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w34"
  },
  {
     "globalpsn":35
    ,"highlightsFindings":[]
    ,"content":"distinct"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w35"
  },
  {
     "globalpsn":36
    ,"highlightsFindings":[]
    ,"content":"causes"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w36"
  },
  {
     "globalpsn":37
    ,"highlightsFindings":[]
    ,"content":"and"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w37"
  },
  {
     "globalpsn":38
    ,"highlightsFindings":[]
    ,"content":"consequences"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w38"
  },
  {
     "globalpsn":39
    ,"highlightsFindings":[]
    ,"content":"."
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w39"
  },
  {
     "globalpsn":40
    ,"highlightsFindings":[]
    ,"content":"With"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w40"
  },
  {
     "globalpsn":41
    ,"highlightsFindings":[]
    ,"content":"bond-based"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w41"
  },
  {
     "globalpsn":42
    ,"highlightsFindings":[]
    ,"content":"attachment,"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w42"
  },
  {
     "globalpsn":43
    ,"highlightsFindings":[]
    ,"content":"people"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w43"
  },
  {
     "globalpsn":44
    ,"highlightsFindings":[]
    ,"content":"feel"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w44"
  },
  {
     "globalpsn":45
    ,"highlightsFindings":[]
    ,"content":"connections"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w45"
  },
  {
     "globalpsn":46
    ,"highlightsFindings":[]
    ,"content":"to"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w46"
  },
  {
     "globalpsn":47
    ,"highlightsFindings":[]
    ,"content":"other"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w47"
  },
  {
     "globalpsn":48
    ,"highlightsFindings":[]
    ,"content":"group"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w48"
  },
  {
     "globalpsn":49
    ,"highlightsFindings":[]
    ,"content":"members,"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w49"
  },
  {
     "globalpsn":50
    ,"highlightsFindings":[]
    ,"content":"while"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w50"
  },
  {
     "globalpsn":51
    ,"highlightsFindings":[]
    ,"content":"with"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w51"
  },
  {
     "globalpsn":52
    ,"highlightsFindings":[]
    ,"content":"identity-based"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w52"
  },
  {
     "globalpsn":53
    ,"highlightsFindings":[]
    ,"content":"attachment"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w53"
  },
  {
     "globalpsn":54
    ,"highlightsFindings":[]
    ,"content":"they"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w54"
  },
  {
     "globalpsn":55
    ,"highlightsFindings":[]
    ,"content":"feel"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w55"
  },
  {
     "globalpsn":56
    ,"highlightsFindings":[]
    ,"content":"connections"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w56"
  },
  {
     "globalpsn":57
    ,"highlightsFindings":[]
    ,"content":"to"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w57"
  },
  {
     "globalpsn":58
    ,"highlightsFindings":[]
    ,"content":"the"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w58"
  },
  {
     "globalpsn":59
    ,"highlightsFindings":[]
    ,"content":"group"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w59"
  },
  {
     "globalpsn":60
    ,"highlightsFindings":[]
    ,"content":"as"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w60"
  },
  {
     "globalpsn":61
    ,"highlightsFindings":[]
    ,"content":"a"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w61"
  },
  {
     "globalpsn":62
    ,"highlightsFindings":[]
    ,"content":"whole"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w62"
  },
  {
     "globalpsn":63
    ,"highlightsFindings":[]
    ,"content":"."
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w63"
  },
  {
     "globalpsn":64
    ,"highlightsFindings":[]
    ,"content":"In"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w64"
  },
  {
     "globalpsn":65
    ,"highlightsFindings":[]
    ,"content":"two"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w65"
  },
  {
     "globalpsn":66
    ,"highlightsFindings":[]
    ,"content":"experiments"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w66"
  },
  {
     "globalpsn":67
    ,"highlightsFindings":[]
    ,"content":"we"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w67"
  },
  {
     "globalpsn":68
    ,"highlightsFindings":[]
    ,"content":"show"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w68"
  },
  {
     "globalpsn":69
    ,"highlightsFindings":[]
    ,"content":"that"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w69"
  },
  {
     "globalpsn":70
    ,"highlightsFindings":[]
    ,"content":"these"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w70"
  },
  {
     "globalpsn":71
    ,"highlightsFindings":[]
    ,"content":"feelings"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w71"
  },
  {
     "globalpsn":72
    ,"highlightsFindings":[]
    ,"content":"of"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w72"
  },
  {
     "globalpsn":73
    ,"highlightsFindings":[]
    ,"content":"attachment"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w73"
  },
  {
     "globalpsn":74
    ,"highlightsFindings":[]
    ,"content":"to"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w74"
  },
  {
     "globalpsn":75
    ,"highlightsFindings":[]
    ,"content":"subgroups"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w75"
  },
  {
     "globalpsn":76
    ,"highlightsFindings":[]
    ,"content":"increase"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w76"
  },
  {
     "globalpsn":77
    ,"highlightsFindings":[]
    ,"content":"loyalty"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w77"
  },
  {
     "globalpsn":78
    ,"highlightsFindings":[]
    ,"content":"to"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w78"
  },
  {
     "globalpsn":79
    ,"highlightsFindings":[]
    ,"content":"the"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w79"
  },
  {
     "globalpsn":80
    ,"highlightsFindings":[]
    ,"content":"larger"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w80"
  },
  {
     "globalpsn":81
    ,"highlightsFindings":[]
    ,"content":"community"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w81"
  },
  {
     "globalpsn":82
    ,"highlightsFindings":[]
    ,"content":"."
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w82"
  },
  {
     "globalpsn":83
    ,"highlightsFindings":[]
    ,"content":"Communication"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w83"
  },
  {
     "globalpsn":84
    ,"highlightsFindings":[]
    ,"content":"with"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w84"
  },
  {
     "globalpsn":85
    ,"highlightsFindings":[]
    ,"content":"other"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w85"
  },
  {
     "globalpsn":86
    ,"highlightsFindings":[]
    ,"content":"people"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w86"
  },
  {
     "globalpsn":87
    ,"highlightsFindings":[]
    ,"content":"in"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w87"
  },
  {
     "globalpsn":88
    ,"highlightsFindings":[]
    ,"content":"a"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w88"
  },
  {
     "globalpsn":89
    ,"highlightsFindings":[]
    ,"content":"subgroup"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w89"
  },
  {
     "globalpsn":90
    ,"highlightsFindings":[]
    ,"content":"but"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w90"
  },
  {
     "globalpsn":91
    ,"highlightsFindings":[]
    ,"content":"not"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w91"
  },
  {
     "globalpsn":92
    ,"highlightsFindings":[]
    ,"content":"simple"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w92"
  },
  {
     "globalpsn":93
    ,"highlightsFindings":[]
    ,"content":"awareness"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w93"
  },
  {
     "globalpsn":94
    ,"highlightsFindings":[]
    ,"content":"of"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w94"
  },
  {
     "globalpsn":95
    ,"highlightsFindings":[]
    ,"content":"them"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w95"
  },
  {
     "globalpsn":96
    ,"highlightsFindings":[]
    ,"content":"increases"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w96"
  },
  {
     "globalpsn":97
    ,"highlightsFindings":[]
    ,"content":"attachment"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w97"
  },
  {
     "globalpsn":98
    ,"highlightsFindings":[]
    ,"content":"to"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w98"
  },
  {
     "globalpsn":99
    ,"highlightsFindings":[]
    ,"content":"the"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w99"
  },
  {
     "globalpsn":100
    ,"highlightsFindings":[]
    ,"content":"larger"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w100"
  },
  {
     "globalpsn":101
    ,"highlightsFindings":[]
    ,"content":"community"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w101"
  },
  {
     "globalpsn":102
    ,"highlightsFindings":[]
    ,"content":"."
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w102"
  },
  {
     "globalpsn":103
    ,"highlightsFindings":[]
    ,"content":"By"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w103"
  },
  {
     "globalpsn":104
    ,"highlightsFindings":[]
    ,"content":"varying"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w104"
  },
  {
     "globalpsn":105
    ,"highlightsFindings":[]
    ,"content":"how"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w105"
  },
  {
     "globalpsn":106
    ,"highlightsFindings":[]
    ,"content":"the"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w106"
  },
  {
     "globalpsn":107
    ,"highlightsFindings":[]
    ,"content":"communication"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w107"
  },
  {
     "globalpsn":108
    ,"highlightsFindings":[]
    ,"content":"is"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w108"
  },
  {
     "globalpsn":109
    ,"highlightsFindings":[]
    ,"content":"structured,"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w109"
  },
  {
     "globalpsn":110
    ,"highlightsFindings":[]
    ,"content":"between"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w110"
  },
  {
     "globalpsn":111
    ,"highlightsFindings":[]
    ,"content":"dyads"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w111"
  },
  {
     "globalpsn":112
    ,"highlightsFindings":[]
    ,"content":"or"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w112"
  },
  {
     "globalpsn":113
    ,"highlightsFindings":[]
    ,"content":"with"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w113"
  },
  {
     "globalpsn":114
    ,"highlightsFindings":[]
    ,"content":"all"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w114"
  },
  {
     "globalpsn":115
    ,"highlightsFindings":[]
    ,"content":"group"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w115"
  },
  {
     "globalpsn":116
    ,"highlightsFindings":[]
    ,"content":"members"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w116"
  },
  {
     "globalpsn":117
    ,"highlightsFindings":[]
    ,"content":"simultaneously,"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w117"
  },
  {
     "globalpsn":118
    ,"highlightsFindings":[]
    ,"content":"the"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w118"
  },
  {
     "globalpsn":119
    ,"highlightsFindings":[]
    ,"content":"experiments"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w119"
  },
  {
     "globalpsn":120
    ,"highlightsFindings":[]
    ,"content":"show"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w120"
  },
  {
     "globalpsn":121
    ,"highlightsFindings":[]
    ,"content":"that"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w121"
  },
  {
     "globalpsn":122
    ,"highlightsFindings":[]
    ,"content":"bond-"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w122"
  },
  {
     "globalpsn":123
    ,"highlightsFindings":[]
    ,"content":"and"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w123"
  },
  {
     "globalpsn":124
    ,"highlightsFindings":[]
    ,"content":"identity-based"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w124"
  },
  {
     "globalpsn":125
    ,"highlightsFindings":[]
    ,"content":"attachment"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w125"
  },
  {
     "globalpsn":126
    ,"highlightsFindings":[]
    ,"content":"have"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w126"
  },
  {
     "globalpsn":127
    ,"highlightsFindings":[]
    ,"content":"different"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w127"
  },
  {
     "globalpsn":128
    ,"highlightsFindings":[]
    ,"content":"causes"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w128"
  },
  {
     "globalpsn":129
    ,"highlightsFindings":[]
    ,"content":"."
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w129"
  },
  {
     "globalpsn":130
    ,"highlightsFindings":[]
    ,"content":"But"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w130"
  },
  {
     "globalpsn":131
    ,"highlightsFindings":[]
    ,"content":"the"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w131"
  },
  {
     "globalpsn":132
    ,"highlightsFindings":[]
    ,"content":"experiments"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w132"
  },
  {
     "globalpsn":133
    ,"highlightsFindings":[]
    ,"content":"show"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w133"
  },
  {
     "globalpsn":134
    ,"highlightsFindings":[]
    ,"content":"no"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w134"
  },
  {
     "globalpsn":135
    ,"highlightsFindings":[]
    ,"content":"evidence"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w135"
  },
  {
     "globalpsn":136
    ,"highlightsFindings":[]
    ,"content":"that"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w136"
  },
  {
     "globalpsn":137
    ,"highlightsFindings":[]
    ,"content":"bond"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w137"
  },
  {
     "globalpsn":138
    ,"highlightsFindings":[]
    ,"content":"and"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w138"
  },
  {
     "globalpsn":139
    ,"highlightsFindings":[]
    ,"content":"identity"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w139"
  },
  {
     "globalpsn":140
    ,"highlightsFindings":[]
    ,"content":"attachment"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w140"
  },
  {
     "globalpsn":141
    ,"highlightsFindings":[]
    ,"content":"have"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w141"
  },
  {
     "globalpsn":142
    ,"highlightsFindings":[]
    ,"content":"different"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w142"
  },
  {
     "globalpsn":143
    ,"highlightsFindings":[]
    ,"content":"consequences"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w143"
  },
  {
     "globalpsn":144
    ,"highlightsFindings":[]
    ,"content":"."
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w144"
  },
  {
     "globalpsn":145
    ,"highlightsFindings":[]
    ,"content":"We"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w145"
  },
  {
     "globalpsn":146
    ,"highlightsFindings":[]
    ,"content":"consider"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w146"
  },
  {
     "globalpsn":147
    ,"highlightsFindings":[]
    ,"content":"both"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w147"
  },
  {
     "globalpsn":148
    ,"highlightsFindings":[]
    ,"content":"theoretical"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w148"
  },
  {
     "globalpsn":149
    ,"highlightsFindings":[]
    ,"content":"and"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w149"
  },
  {
     "globalpsn":150
    ,"highlightsFindings":[]
    ,"content":"methodological"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w150"
  },
  {
     "globalpsn":151
    ,"highlightsFindings":[]
    ,"content":"reasons"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w151"
  },
  {
     "globalpsn":152
    ,"highlightsFindings":[]
    ,"content":"why"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w152"
  },
  {
     "globalpsn":153
    ,"highlightsFindings":[]
    ,"content":"the"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w153"
  },
  {
     "globalpsn":154
    ,"highlightsFindings":[]
    ,"content":"consequences"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w154"
  },
  {
     "globalpsn":155
    ,"highlightsFindings":[]
    ,"content":"of"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w155"
  },
  {
     "globalpsn":156
    ,"highlightsFindings":[]
    ,"content":"bond-based"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w156"
  },
  {
     "globalpsn":157
    ,"highlightsFindings":[]
    ,"content":"and"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w157"
  },
  {
     "globalpsn":158
    ,"highlightsFindings":[]
    ,"content":"identity-based"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w158"
  },
  {
     "globalpsn":159
    ,"highlightsFindings":[]
    ,"content":"attachment"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w159"
  },
  {
     "globalpsn":160
    ,"highlightsFindings":[]
    ,"content":"are"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w160"
  },
  {
     "globalpsn":161
    ,"highlightsFindings":[]
    ,"content":"so"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w161"
  },
  {
     "globalpsn":162
    ,"highlightsFindings":[]
    ,"content":"similar"
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w162"
  },
  {
     "globalpsn":163
    ,"highlightsFindings":[]
    ,"content":"."
    ,"highlightsMechanism":[]
    ,"highlightsPurpose":[]
    ,"highlightsBackground":[]
    ,"_id":"w163"
  }]

// Template.tutorialSentence.helpers({
//     sampleWords : function() {
//         var sentence = "Suntime has advantages over each of these because it records the intensity of sun exposure with the time of day of that exposure, provides a permanent paper record and operates with no batteries or electronics."
//         var words = sentence.split(" ");
//         var wordObjects = [];
//         for (i=0; i < words.length; i++) {
//             var w = {_id: i, content: words[i]}
//             wordObjects.push(w);
//         }
//         logger.trace("Tutorial words: " + JSON.stringify(wordObjects))
//         return wordObjects;
//     }
// });

// Template.tutorialSentence.events({
//     'click .key-option': function(event) {
//         var selection = event.currentTarget;
//         // var keyType = selection.innerText;
//         // console.log(selection);
//         var word = selection.parentNode.previousElementSibling;
//         // console.log(word);
//         var wordID = "#" + word.id;
//         var wordText = $(wordID).text().trim();
//         userID = Session.get("currentUser")._id;
//         logger.trace(userID + " clicked on " + wordText + " with id " + wordID);
//         if (selection.classList.contains("purp")) {
//             $(wordID).addClass('key-purpose');
//             $(wordID).removeClass('key-mechanism');
//             $(wordID).removeClass('key-neutral');
//             EventLogger.logMarkTutorialWord(wordText, "Purpose");
//         } else if (selection.classList.contains("mech")) {
//             $(wordID).removeClass('key-purpose');
//             $(wordID).addClass('key-mechanism');
//             $(wordID).removeClass('key-neutral');
//             EventLogger.logMarkTutorialWord(wordText, "Mechanism");
//         } else {
//             $(wordID).removeClass('key-purpose');
//             $(wordID).removeClass('key-mechanism');
//             $(wordID).addClass('key-neutral');
//             EventLogger.logMarkTutorialWord(wordText, "Unmark");
//         }
//     }
// });
